# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created: Mon Jun 22 01:19:21 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainScreen(object):
    def setupUi(self, mainScreen):
        mainScreen.setObjectName("mainScreen")
        mainScreen.resize(990, 512)
        mainScreen.setStyleSheet("background-image: url(:/mainBG/media/blurredColors.jpeg);")
        self.pagesSwitch = QtGui.QStackedWidget(mainScreen)
        self.pagesSwitch.setGeometry(QtCore.QRect(0, 30, 990, 482))
        self.pagesSwitch.setObjectName("pagesSwitch")
        self.homePage = QtGui.QWidget()
        self.homePage.setObjectName("homePage")
        self.iconsGroup = QtGui.QGroupBox(self.homePage)
        self.iconsGroup.setGeometry(QtCore.QRect(95, 41, 800, 400))
        self.iconsGroup.setStyleSheet("border:none;\n"
"background:none;")
        self.iconsGroup.setTitle("")
        self.iconsGroup.setObjectName("iconsGroup")
        self.phoneButton = QtGui.QPushButton(self.iconsGroup)
        self.phoneButton.setGeometry(QtCore.QRect(100, 60, 100, 100))
        self.phoneButton.setBaseSize(QtCore.QSize(90, 90))
        self.phoneButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.phoneButton.setAccessibleName("")
        self.phoneButton.setAutoFillBackground(False)
        self.phoneButton.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.phoneButton.setText("")
        self.phoneButton.setIconSize(QtCore.QSize(100, 100))
        self.phoneButton.setAutoDefault(True)
        self.phoneButton.setDefault(False)
        self.phoneButton.setObjectName("phoneButton")
        self.fmButton = QtGui.QPushButton(self.iconsGroup)
        self.fmButton.setGeometry(QtCore.QRect(350, 60, 100, 100))
        self.fmButton.setBaseSize(QtCore.QSize(90, 90))
        self.fmButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fmButton.setAccessibleName("")
        self.fmButton.setAutoFillBackground(False)
        self.fmButton.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.fmButton.setText("")
        self.fmButton.setIconSize(QtCore.QSize(100, 100))
        self.fmButton.setAutoDefault(True)
        self.fmButton.setDefault(False)
        self.fmButton.setObjectName("fmButton")
        self.musicButton = QtGui.QPushButton(self.iconsGroup)
        self.musicButton.setGeometry(QtCore.QRect(610, 60, 100, 100))
        self.musicButton.setBaseSize(QtCore.QSize(90, 90))
        self.musicButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.musicButton.setAccessibleName("")
        self.musicButton.setAutoFillBackground(False)
        self.musicButton.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.musicButton.setText("")
        self.musicButton.setIconSize(QtCore.QSize(100, 100))
        self.musicButton.setAutoDefault(True)
        self.musicButton.setDefault(False)
        self.musicButton.setObjectName("musicButton")
        self.gpsButton = QtGui.QPushButton(self.iconsGroup)
        self.gpsButton.setGeometry(QtCore.QRect(100, 250, 100, 100))
        self.gpsButton.setBaseSize(QtCore.QSize(90, 90))
        self.gpsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gpsButton.setAccessibleName("")
        self.gpsButton.setAutoFillBackground(False)
        self.gpsButton.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.gpsButton.setText("")
        self.gpsButton.setIconSize(QtCore.QSize(100, 100))
        self.gpsButton.setAutoDefault(True)
        self.gpsButton.setDefault(False)
        self.gpsButton.setObjectName("gpsButton")
        self.bluetoothButton = QtGui.QPushButton(self.iconsGroup)
        self.bluetoothButton.setGeometry(QtCore.QRect(350, 250, 100, 100))
        self.bluetoothButton.setBaseSize(QtCore.QSize(90, 90))
        self.bluetoothButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bluetoothButton.setAccessibleName("")
        self.bluetoothButton.setAutoFillBackground(False)
        self.bluetoothButton.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.bluetoothButton.setText("")
        self.bluetoothButton.setIconSize(QtCore.QSize(100, 100))
        self.bluetoothButton.setAutoDefault(True)
        self.bluetoothButton.setDefault(False)
        self.bluetoothButton.setObjectName("bluetoothButton")
        self.settingsButton = QtGui.QPushButton(self.iconsGroup)
        self.settingsButton.setGeometry(QtCore.QRect(610, 250, 100, 100))
        self.settingsButton.setBaseSize(QtCore.QSize(90, 90))
        self.settingsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settingsButton.setAccessibleName("")
        self.settingsButton.setAutoFillBackground(False)
        self.settingsButton.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.settingsButton.setText("")
        self.settingsButton.setIconSize(QtCore.QSize(100, 100))
        self.settingsButton.setAutoDefault(True)
        self.settingsButton.setDefault(False)
        self.settingsButton.setObjectName("settingsButton")
        self.pagesSwitch.addWidget(self.homePage)
        self.phonePage = QtGui.QWidget()
        self.phonePage.setObjectName("phonePage")
        self.phoneLabel = QtGui.QLabel(self.phonePage)
        self.phoneLabel.setGeometry(QtCore.QRect(210, 60, 571, 291))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setAutoFillBackground(False)
        self.phoneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phoneLabel.setObjectName("phoneLabel")
        self.homeButtonPh = QtGui.QPushButton(self.phonePage)
        self.homeButtonPh.setGeometry(QtCore.QRect(470, 430, 50, 50))
        self.homeButtonPh.setBaseSize(QtCore.QSize(50, 50))
        self.homeButtonPh.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homeButtonPh.setAccessibleName("")
        self.homeButtonPh.setAutoFillBackground(False)
        self.homeButtonPh.setStyleSheet("border:none;\n"
"border-radius: 80px;")
        self.homeButtonPh.setText("")
        self.homeButtonPh.setIconSize(QtCore.QSize(100, 100))
        self.homeButtonPh.setAutoDefault(True)
        self.homeButtonPh.setDefault(False)
        self.homeButtonPh.setObjectName("homeButtonPh")
        self.pagesSwitch.addWidget(self.phonePage)
        self.fmPage = QtGui.QWidget()
        self.fmPage.setObjectName("fmPage")
        self.homeButtonFm = QtGui.QPushButton(self.fmPage)
        self.homeButtonFm.setGeometry(QtCore.QRect(470, 430, 50, 50))
        self.homeButtonFm.setBaseSize(QtCore.QSize(50, 50))
        self.homeButtonFm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homeButtonFm.setAccessibleName("")
        self.homeButtonFm.setAutoFillBackground(False)
        self.homeButtonFm.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.homeButtonFm.setText("")
        self.homeButtonFm.setIconSize(QtCore.QSize(100, 100))
        self.homeButtonFm.setAutoDefault(True)
        self.homeButtonFm.setDefault(False)
        self.homeButtonFm.setObjectName("homeButtonFm")
        self.fmLabel = QtGui.QLabel(self.fmPage)
        self.fmLabel.setGeometry(QtCore.QRect(210, 60, 571, 291))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.fmLabel.setFont(font)
        self.fmLabel.setAutoFillBackground(False)
        self.fmLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fmLabel.setObjectName("fmLabel")
        self.pagesSwitch.addWidget(self.fmPage)
        self.musicPage = QtGui.QWidget()
        self.musicPage.setObjectName("musicPage")
        self.homeButtonMs = QtGui.QPushButton(self.musicPage)
        self.homeButtonMs.setGeometry(QtCore.QRect(470, 430, 50, 50))
        self.homeButtonMs.setBaseSize(QtCore.QSize(50, 50))
        self.homeButtonMs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homeButtonMs.setAccessibleName("")
        self.homeButtonMs.setAutoFillBackground(False)
        self.homeButtonMs.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.homeButtonMs.setText("")
        self.homeButtonMs.setIconSize(QtCore.QSize(100, 100))
        self.homeButtonMs.setAutoDefault(True)
        self.homeButtonMs.setDefault(False)
        self.homeButtonMs.setObjectName("homeButtonMs")
        self.musicLabel = QtGui.QLabel(self.musicPage)
        self.musicLabel.setGeometry(QtCore.QRect(210, 60, 571, 291))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.musicLabel.setFont(font)
        self.musicLabel.setAutoFillBackground(False)
        self.musicLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.musicLabel.setObjectName("musicLabel")
        self.pagesSwitch.addWidget(self.musicPage)
        self.gpsPage = QtGui.QWidget()
        self.gpsPage.setObjectName("gpsPage")
        self.homeButtonGp = QtGui.QPushButton(self.gpsPage)
        self.homeButtonGp.setGeometry(QtCore.QRect(470, 430, 50, 50))
        self.homeButtonGp.setBaseSize(QtCore.QSize(50, 50))
        self.homeButtonGp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homeButtonGp.setAccessibleName("")
        self.homeButtonGp.setAutoFillBackground(False)
        self.homeButtonGp.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.homeButtonGp.setText("")
        self.homeButtonGp.setIconSize(QtCore.QSize(100, 100))
        self.homeButtonGp.setAutoDefault(True)
        self.homeButtonGp.setDefault(False)
        self.homeButtonGp.setObjectName("homeButtonGp")
        self.gpsLabel = QtGui.QLabel(self.gpsPage)
        self.gpsLabel.setGeometry(QtCore.QRect(210, 60, 571, 291))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.gpsLabel.setFont(font)
        self.gpsLabel.setAutoFillBackground(False)
        self.gpsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gpsLabel.setObjectName("gpsLabel")
        self.pagesSwitch.addWidget(self.gpsPage)
        self.bluetoothPage = QtGui.QWidget()
        self.bluetoothPage.setObjectName("bluetoothPage")
        self.homeButtonBl = QtGui.QPushButton(self.bluetoothPage)
        self.homeButtonBl.setGeometry(QtCore.QRect(470, 430, 50, 50))
        self.homeButtonBl.setBaseSize(QtCore.QSize(50, 50))
        self.homeButtonBl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homeButtonBl.setAccessibleName("")
        self.homeButtonBl.setAutoFillBackground(False)
        self.homeButtonBl.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.homeButtonBl.setText("")
        self.homeButtonBl.setIconSize(QtCore.QSize(100, 100))
        self.homeButtonBl.setAutoDefault(True)
        self.homeButtonBl.setDefault(False)
        self.homeButtonBl.setObjectName("homeButtonBl")
        self.bluetoothLabel = QtGui.QLabel(self.bluetoothPage)
        self.bluetoothLabel.setGeometry(QtCore.QRect(210, 60, 571, 291))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.bluetoothLabel.setFont(font)
        self.bluetoothLabel.setAutoFillBackground(False)
        self.bluetoothLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bluetoothLabel.setObjectName("bluetoothLabel")
        self.pagesSwitch.addWidget(self.bluetoothPage)
        self.settingsPage = QtGui.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.homeButtonSt = QtGui.QPushButton(self.settingsPage)
        self.homeButtonSt.setGeometry(QtCore.QRect(470, 430, 50, 50))
        self.homeButtonSt.setBaseSize(QtCore.QSize(50, 50))
        self.homeButtonSt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homeButtonSt.setAccessibleName("")
        self.homeButtonSt.setAutoFillBackground(False)
        self.homeButtonSt.setStyleSheet("border:none;\n"
"border-radius: 50px;")
        self.homeButtonSt.setText("")
        self.homeButtonSt.setIconSize(QtCore.QSize(100, 100))
        self.homeButtonSt.setAutoDefault(True)
        self.homeButtonSt.setDefault(False)
        self.homeButtonSt.setObjectName("homeButtonSt")
        self.settingsLabel = QtGui.QLabel(self.settingsPage)
        self.settingsLabel.setGeometry(QtCore.QRect(210, 60, 571, 291))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setAutoFillBackground(False)
        self.settingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settingsLabel.setObjectName("settingsLabel")
        self.pagesSwitch.addWidget(self.settingsPage)
        self.infoGroup = QtGui.QGroupBox(mainScreen)
        self.infoGroup.setGeometry(QtCore.QRect(0, 0, 990, 30))
        self.infoGroup.setStyleSheet("border:none;\n"
"background:none;")
        self.infoGroup.setTitle("")
        self.infoGroup.setObjectName("infoGroup")
        self.dateText = QtGui.QLabel(self.infoGroup)
        self.dateText.setGeometry(QtCore.QRect(740, 5, 151, 20))
        self.dateText.setText("")
        self.dateText.setObjectName("dateText")
        self.timeText = QtGui.QLabel(self.infoGroup)
        self.timeText.setGeometry(QtCore.QRect(890, 5, 81, 20))
        self.timeText.setText("")
        self.timeText.setObjectName("timeText")

        self.retranslateUi(mainScreen)
        self.pagesSwitch.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainScreen)

    def retranslateUi(self, mainScreen):
        mainScreen.setWindowTitle(QtGui.QApplication.translate("mainScreen", "Infotainment System", None, QtGui.QApplication.UnicodeUTF8))
        self.phoneLabel.setText(QtGui.QApplication.translate("mainScreen", "Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.fmLabel.setText(QtGui.QApplication.translate("mainScreen", "FM", None, QtGui.QApplication.UnicodeUTF8))
        self.musicLabel.setText(QtGui.QApplication.translate("mainScreen", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.gpsLabel.setText(QtGui.QApplication.translate("mainScreen", "GPS", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothLabel.setText(QtGui.QApplication.translate("mainScreen", "Bluetooth", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsLabel.setText(QtGui.QApplication.translate("mainScreen", "Settings", None, QtGui.QApplication.UnicodeUTF8))

